brew "git"
brew "git-extras"
brew "hub"
brew "libxml2"
brew "postgresql"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "shellcheck"
brew "syncthing", restart_service: true
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "wget"
