#!/usr/bin/env bash

set -e


function get_hosts_entry {
  echo $(host -t A ${2} ${1} | awk '/has.*address/ {print $NF; exit}') ${2}
}

test_dns_server=10.2.0.2
if nc -G1 -w1 -z ${test_dns_server} 53 2>/dev/null; then
  cat > /tmp/autohosts <<EOF
# AUTO TEST START
$(get_hosts_entry $test_dns_server redis.advancedagtest.com)
$(get_hosts_entry $test_dns_server tfs-redis.advancedagtest.com)
$(get_hosts_entry $test_dns_server postgres.advancedagtest.com)
$(get_hosts_entry $test_dns_server mssql.advancedagtest.com)
$(get_hosts_entry $test_dns_server farmgate-mysql.advancedagtest.com)
$(get_hosts_entry $test_dns_server ds.bayes.advancedagtest.com)
$(get_hosts_entry $test_dns_server sonar.advancedagrilytics.com)
# AUTO TEST END
EOF

  cat ~/.pw | sudo -S -p "" sed -i.backup '/# AUTO TEST START/,/# AUTO TEST END/d' /etc/hosts
  cat ~/.pw | sudo -S -p "" cat /tmp/autohosts >> /etc/hosts
fi

prod_dns_server=172.31.0.2
if nc -G1 -w1 -z ${prod_dns_server} 53; then
  cat > /tmp/autohosts <<EOF
# AUTO PROD START
$(get_hosts_entry $prod_dns_server redis.advancedag.com)
$(get_hosts_entry $prod_dns_server postgres.advancedag.com)
$(get_hosts_entry $prod_dns_server mssql.advancedag.com)
$(get_hosts_entry $prod_dns_server farmgate-mysql.advancedag.com)
$(get_hosts_entry $prod_dns_server ds.bayes.advancedag.com)
# AUTO PROD END
EOF

  cat ~/.pw | sudo -S -p "" sed -i.backup '/# AUTO PROD START/,/# AUTO PROD END/d' /etc/hosts
  cat ~/.pw | sudo -S -p "" cat /tmp/autohosts >> /etc/hosts
fi

