#!/usr/bin/env bash

result=""

if nc -G1 -w1 -z "10.2.0.2" 53 2>/dev/null; then
  result="test"
fi

if nc -G1 -w1 -z "172.31.0.2" 53 2>/dev/null; then
  [[ -n "$result" ]] && result+=" | "
  result+="prod"
fi

echo "$result"
