alias ls='ls -GFh'
alias ll='ls -GFhl'
alias la='ls -GFhla'
alias l.='ls -GFhd .*'
alias tree="find . -print | sed -e 's;[^/]*/;|___;g;s;___|; |;g'"
alias rake="noglob rake"
alias bi="bundle install --path vendor"
alias be="bundle exec"
alias rs="bundle exec rails server"
alias rc="bundle exec rails console"
alias rg="bundle exec rails generate"
