#!/opt/homebrew/bin/node

import fs from 'node:fs';
import { spawn } from 'node:child_process';

const stdout = [];
const stderr = [];

const speedtest = spawn('/opt/homebrew/bin/speedtest', ['-f', 'json']);

speedtest.stdout.on('data', (data) => stdout.push(data.toString()));
speedtest.stderr.on('data', (data) => stderr.push(data.toString()));

speedtest.on('close', (code) => {
  if (stderr.length) console.error(stderr.join(''))
  if (stdout.length) console.log(stderr.join(''))

  if (!code) {
    const historyFile = './local-history.json';
    const history = fs.existsSync(historyFile)
      ? JSON.parse(fs.readFileSync(historyFile))
      : [];
    history.unshift(JSON.parse(stdout.join('')));

    const stream = fs.createWriteStream(historyFile);
    stream.write('[\n');

    history.forEach((line, i) => {
      stream.write('  ');
      stream.write(JSON.stringify(line));
      if (i + 1 < history.length) stream.write(',');
      stream.write('\n');
    });

    stream.write(']\n');
    stream.end();
  }
});
